name: coolors_palette
description: A Package that helps you to get your color palette from coolors.co to your project
version: 1.0.0
homepage: https://github.com/imertgul/coolors_palette

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
